[package]
name = "spdcp"
version = "0.1.0"
description = "A library for parsing docparse comment range"
authors = ["rumblefrog <contact@zhenyangli.me>"]
repository = "https://github.com/rumblefrog/sp-dcp"
license = "GPL-3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
